Repository codestates-seb/seb41_main_005, pull requests merged in 2023-01, with the labels that each got.

#12 [feat / fix] 운영 서버 구축 과정에서 버그 수정 / 일부 설정 추가 및 수정
  server/src/main/java/com/gigker/server/domain/content/entity/ContentApply.java
  server/src/main/java/com/gigker/server/domain/member/entity/Member.java
  server/src/main/java/com/gigker/server/global/config/P6SpySqlFormatter.java
  server/src/main/resources/application.yml
Labels: fix, feat, 🛠️ BE

#15 [ContentApply] CRUD 추가
  server/src/main/java/com/gigker/server/domain/content/controller/ContentApplyController.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentApplyDto.java
  server/src/main/java/com/gigker/server/domain/content/entity/ContentApply.java
  server/src/main/java/com/gigker/server/domain/content/mapper/ContentApplyMapper.java
  server/src/main/java/com/gigker/server/domain/content/repository/ContentApplyRepository.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentApplyService.java
  server/src/main/java/com/gigker/server/global/exception/ExceptionCode.java
  server/src/test/java/com/gigker/server/ServerApplicationTests.java
Labels: fix, feat, 🛠️ BE

#26 Be/feat/content
  server/src/main/java/com/gigker/server/domain/common/CustomBeanUtils.java
  server/src/main/java/com/gigker/server/domain/content/controller/ContentController.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentDto.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentTagResponseDto.java
  server/src/main/java/com/gigker/server/domain/content/entity/Content.java
  server/src/main/java/com/gigker/server/domain/content/entity/ContentTag.java
  server/src/main/java/com/gigker/server/domain/content/mapper/ContentMapper.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentService.java
  server/src/main/java/com/gigker/server/domain/member/service/MemberService.java
  server/src/main/java/com/gigker/server/domain/tag/entity/Tag.java
  server/src/main/java/com/gigker/server/global/exception/ExceptionCode.java
Labels: feat, 🛠️ BE

#24 [Review] 리뷰 CRUD 구성
  server/src/main/java/com/gigker/server/domain/common/LikeType.java
  server/src/main/java/com/gigker/server/domain/review/controller/ReviewController.java
  server/src/main/java/com/gigker/server/domain/review/dto/ReviewDto.java
  server/src/main/java/com/gigker/server/domain/review/entity/Review.java
  server/src/main/java/com/gigker/server/domain/review/mapper/ReviewMapper.java
  server/src/main/java/com/gigker/server/domain/review/repository/ReviewRepository.java
  server/src/main/java/com/gigker/server/domain/review/service/ReviewService.java
Labels: feat, 🛠️ BE

#30 [MEMBER]회원가입 이미지 서버 구축 및 DB URL저장
  server/build.gradle
  server/src/main/java/com/gigker/server/domain/content/mapper/ContentMapper.java
  server/src/main/java/com/gigker/server/domain/member/controller/MemberController.java
  server/src/main/java/com/gigker/server/domain/member/dto/MemberPostDto.java
  server/src/main/java/com/gigker/server/domain/member/entity/Member.java
  server/src/main/java/com/gigker/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/gigker/server/domain/member/mapper/ProfileMapper.java
  server/src/main/java/com/gigker/server/domain/member/service/MemberService.java
  server/src/main/java/com/gigker/server/domain/review/mapper/ReviewMapper.java
  server/src/main/java/com/gigker/server/global/s3/config/S3Config.java
  server/src/main/java/com/gigker/server/global/s3/service/S3Service.java
  server/src/main/resources/application.yml
Labels: feat, 🛠️ BE, deploy

#28 [ContentApply] 지원 및 지원 승인 기능 구현
  server/src/main/java/com/gigker/server/domain/content/controller/ContentApplyController.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentApplyDto.java
  server/src/main/java/com/gigker/server/domain/content/entity/Content.java
  server/src/main/java/com/gigker/server/domain/content/entity/ContentApply.java
  server/src/main/java/com/gigker/server/domain/content/mapper/ContentApplyMapper.java
  server/src/main/java/com/gigker/server/domain/content/repository/ContentApplyRepository.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentApplyService.java
  server/src/main/java/com/gigker/server/global/exception/ExceptionCode.java
  server/src/main/java/com/gigker/server/global/exception/controller/GlobalExceptionAdvice.java
  server/src/test/java/com/gigker/server/domain/contentApply/service/ContentApplyServiceTest.java
  server/src/test/java/com/gigker/server/domain/stub/ContentApplyStubData.java
  server/src/test/java/com/gigker/server/domain/stub/ContentStubData.java
  server/src/test/java/com/gigker/server/domain/stub/MemberStubData.java
Labels: feat, 🛠️ BE

#38 Be/feat/tag
  server/src/main/java/com/gigker/server/domain/content/controller/ContentController.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentDto.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentPatchDto.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentPostDto.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentResponseDto.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentTagResponseDto.java
  server/src/main/java/com/gigker/server/domain/content/entity/Content.java
  server/src/main/java/com/gigker/server/domain/content/entity/ContentTag.java
  server/src/main/java/com/gigker/server/domain/content/mapper/ContentMapper.java
  server/src/main/java/com/gigker/server/domain/content/repository/ContentRepository.java
  server/src/main/java/com/gigker/server/domain/content/repository/ContentTagRepository.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentService.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentTagService.java
  server/src/main/java/com/gigker/server/domain/review/entity/Review.java
  server/src/main/java/com/gigker/server/domain/tag/controller/TagController.java
  server/src/main/java/com/gigker/server/domain/tag/dto/TagPostDto.java
  server/src/main/java/com/gigker/server/domain/tag/dto/TagResponseDto.java
  server/src/main/java/com/gigker/server/domain/tag/entity/Tag.java
  server/src/main/java/com/gigker/server/domain/tag/mapper/TagMapper.java
  server/src/main/java/com/gigker/server/domain/tag/repository/TagRepository.java
  server/src/main/java/com/gigker/server/domain/tag/service/TagService.java
Labels: 🛠️ BE

#39 [ContentApply] 지원 요청 목록 조회 및 삭제 기능 구현 + 서비스 로직 추가
  server/src/main/java/com/gigker/server/domain/content/controller/ContentApplyController.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentApplyDto.java
  server/src/main/java/com/gigker/server/domain/content/mapper/ContentApplyMapper.java
  server/src/main/java/com/gigker/server/domain/content/repository/ContentApplyRepository.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentApplyService.java
  server/src/main/java/com/gigker/server/global/exception/ExceptionCode.java
  server/src/test/java/com/gigker/server/domain/contentApply/service/ContentApplyServiceTest.java
  server/src/test/java/com/gigker/server/domain/stub/ContentApplyStubData.java
  server/src/test/java/com/gigker/server/domain/stub/ContentStubData.java
Labels: feat, 🛠️ BE

#47 Be/feat/tag
  server/src/main/java/com/gigker/server/ServerApplication.java
  server/src/main/java/com/gigker/server/domain/content/controller/ContentController.java
  server/src/main/java/com/gigker/server/domain/content/repository/ContentRepository.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentService.java
  server/src/main/java/com/gigker/server/domain/tag/controller/TagController.java
Labels: 🛠️ BE

#49 [MEMBER] 로그인 및 프로필 수정기능
  server/src/main/java/com/gigker/server/domain/member/controller/MemberController.java
  server/src/main/java/com/gigker/server/domain/member/dto/MemberPatchDto.java
  server/src/main/java/com/gigker/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/gigker/server/domain/member/service/MemberService.java
  server/src/main/java/com/gigker/server/global/exception/ExceptionCode.java
  server/src/main/java/com/gigker/server/global/s3/service/S3Service.java
  server/src/main/resources/application.yml
Labels: feat, 🛠️ BE

#54 Be/feat/tag
  server/src/main/java/com/gigker/server/ServerApplication.java
  server/src/main/java/com/gigker/server/domain/content/controller/ContentController.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentPatchDto.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentPostDto.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentResponseDto.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentTagResponseDto.java
  server/src/main/java/com/gigker/server/domain/content/entity/Content.java
  server/src/main/java/com/gigker/server/domain/content/entity/ContentTag.java
  server/src/main/java/com/gigker/server/domain/content/mapper/ContentMapper.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentService.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentTagService.java
  server/src/main/java/com/gigker/server/domain/tag/dto/TagResponseDto.java
  server/src/main/java/com/gigker/server/domain/tag/entity/Tag.java
Labels: 🛠️ BE

#56 [ContentApply] 전체 조회에 대한 Response 수정
  server/src/main/java/com/gigker/server/domain/content/controller/ContentApplyController.java
  server/src/main/java/com/gigker/server/domain/content/controller/ContentController.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentApplyResponseDto.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentResponseDto.java
  server/src/main/java/com/gigker/server/domain/content/entity/Content.java
  server/src/main/java/com/gigker/server/domain/content/entity/ContentApply.java
  server/src/main/java/com/gigker/server/domain/content/mapper/ContentApplyMapper.java
  server/src/main/java/com/gigker/server/domain/content/mapper/ContentMapper.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentApplyService.java
  server/src/main/java/com/gigker/server/global/dto/MultiResponseDto.java
Labels: feat, 🛠️ BE

#68 Be/feat/content tag
  server/src/main/java/com/gigker/server/domain/common/WorkTimeMapper.java
  server/src/main/java/com/gigker/server/domain/content/controller/ContentController.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentPatchDto.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentPostDto.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentResponseDto.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentTagResponseDto.java
  server/src/main/java/com/gigker/server/domain/content/entity/Content.java
  server/src/main/java/com/gigker/server/domain/content/entity/ContentTag.java
  server/src/main/java/com/gigker/server/domain/content/mapper/ContentMapper.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentService.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentTagService.java
  server/src/main/java/com/gigker/server/domain/tag/controller/TagController.java
  server/src/main/java/com/gigker/server/domain/tag/dto/TagResponseDto.java
  server/src/main/java/com/gigker/server/domain/tag/entity/Tag.java
Labels: 🛠️ Backend

#69 [Review] 리뷰 작성 기능 구현
  server/src/main/java/com/gigker/server/domain/content/controller/ContentApplyController.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentApplyResponseDto.java
  server/src/main/java/com/gigker/server/domain/content/mapper/ContentApplyMapper.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentApplyService.java
  server/src/main/java/com/gigker/server/domain/member/controller/MemberController.java
  server/src/main/java/com/gigker/server/domain/member/dto/MemberProfileResponseDto.java
  server/src/main/java/com/gigker/server/domain/member/entity/Member.java
  server/src/main/java/com/gigker/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/gigker/server/domain/review/controller/ReviewController.java
  server/src/main/java/com/gigker/server/domain/review/dto/ReviewDto.java
  server/src/main/java/com/gigker/server/domain/review/entity/Review.java
  server/src/main/java/com/gigker/server/domain/review/mapper/ReviewMapper.java
  server/src/main/java/com/gigker/server/domain/review/repository/ReviewRepository.java
  server/src/main/java/com/gigker/server/domain/review/service/ReviewService.java
  server/src/main/java/com/gigker/server/global/config/SecurityConfiguration.java
  server/src/main/java/com/gigker/server/global/exception/ExceptionCode.java
  server/src/main/resources/application.yml
  server/src/main/resources/data.sql
  server/src/test/java/com/gigker/server/domain/contentApply/ContentApplyServiceTest.java
  server/src/test/java/com/gigker/server/domain/stub/ContentStubData.java
Labels: feat, 🛠️ Backend

#71 Be/feat/category
  server/src/main/java/com/gigker/server/domain/category/controller/categoryController.java
  server/src/main/java/com/gigker/server/domain/category/entity/Category.java
  server/src/main/java/com/gigker/server/domain/category/repository/CategoryRepository.java
  server/src/main/java/com/gigker/server/domain/common/WorkTime.java
  server/src/main/java/com/gigker/server/domain/common/WorkTimeResponseDto.java
  server/src/main/java/com/gigker/server/domain/content/controller/ContentController.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentPatchDto.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentPostDto.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentResponseDto.java
  server/src/main/java/com/gigker/server/domain/content/entity/Content.java
  server/src/main/java/com/gigker/server/domain/content/mapper/ContentMapper.java
Labels: 🛠️ Backend

#77 [Review] 리뷰 조회 및 삭제 기능 구현 +@
  server/src/main/java/com/gigker/server/domain/content/controller/ContentApplyController.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentResponseDto.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentApplyService.java
  server/src/main/java/com/gigker/server/domain/location/entity/Location.java
  server/src/main/java/com/gigker/server/domain/location/repository/LocationRepository.java
  server/src/main/java/com/gigker/server/domain/member/dto/MemberProfileResponseDto.java
  server/src/main/java/com/gigker/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/gigker/server/domain/review/controller/ReviewController.java
  server/src/main/java/com/gigker/server/domain/review/dto/ReviewDto.java
  server/src/main/java/com/gigker/server/domain/review/entity/Review.java
  server/src/main/java/com/gigker/server/domain/review/repository/ReviewRepository.java
  server/src/main/java/com/gigker/server/domain/review/service/ReviewService.java
  server/src/main/resources/data.sql
  server/src/test/java/com/gigker/server/domain/contentApply/ContentApplyServiceTest.java
Labels: feat, 🛠️ Backend

#75 Be/feat/category
  server/src/main/java/com/gigker/server/domain/category/controller/CategoryController.java
  server/src/main/java/com/gigker/server/domain/category/entity/Category.java
  server/src/main/java/com/gigker/server/domain/category/repository/CategoryRepository.java
  server/src/main/java/com/gigker/server/domain/category/service/CategoryService.java
  server/src/main/java/com/gigker/server/domain/content/controller/ContentController.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentPatchDto.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentPostDto.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentResponseDto.java
  server/src/main/java/com/gigker/server/domain/content/entity/Content.java
  server/src/main/java/com/gigker/server/domain/content/mapper/ContentMapper.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentService.java
  server/src/main/java/com/gigker/server/global/exception/ExceptionCode.java
Labels: 🛠️ Backend

#83 Redux 리팩토링 & Redux-persist
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Navigation.tsx
  client/src/components/Profile.tsx
  client/src/components/hire/HireArticle.tsx
  client/src/components/hire/HireDropDown.tsx
  client/src/components/hunting/HuntingArticle.tsx
  client/src/components/hunting/HuntingDropDown.tsx
  client/src/components/login/LogInForm.tsx
  client/src/components/signup/SignUpForm.tsx
  client/src/index.tsx
  client/src/util/reducer.ts
  client/src/util/redux/DropDown.ts
  client/src/util/redux/LogIn.ts
  client/src/util/redux/SignUp.ts
  client/src/util/redux/Validation.ts
  client/src/util/redux/index.ts
  client/src/util/scrollRestoration.ts
  client/src/util/store.ts
  client/src/util/types.ts
Labels: refactor, feat, ✨ Frontend

#84 [Location] 기능 구현 및 미사용 클래스파일 삭제
  server/src/main/java/com/gigker/server/domain/category/controller/CategoryController.java
  server/src/main/java/com/gigker/server/domain/category/repository/CategoryRepository.java
  server/src/main/java/com/gigker/server/domain/common/WorkTimeResponseDto.java
  server/src/main/java/com/gigker/server/domain/content/controller/ContentController.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentPatchDto.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentPostDto.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentResponseDto.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentTagResponseDto.java
  server/src/main/java/com/gigker/server/domain/content/entity/Content.java
  server/src/main/java/com/gigker/server/domain/content/mapper/ContentMapper.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentService.java
  server/src/main/java/com/gigker/server/domain/location/dto/LocationResponseDto.java
  server/src/main/java/com/gigker/server/domain/location/entity/Location.java
  server/src/main/java/com/gigker/server/domain/location/repository/LocationRepository.java
  server/src/main/java/com/gigker/server/domain/location/service/LocationService.java
  server/src/main/java/com/gigker/server/domain/tag/controller/TagController.java
  server/src/main/java/com/gigker/server/domain/tag/dto/TagPostDto.java
  server/src/main/java/com/gigker/server/domain/tag/dto/TagResponseDto.java
  server/src/main/java/com/gigker/server/domain/tag/mapper/TagMapper.java
  server/src/main/java/com/gigker/server/domain/tag/service/TagService.java
  server/src/main/java/com/gigker/server/global/exception/ExceptionCode.java
  server/src/main/resources/data.sql
Labels: 🛠️ Backend

#85 [ContentApply/Review] Authentication 적용
  server/src/main/java/com/gigker/server/domain/content/controller/ContentApplyController.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentApplyResponseDto.java
  server/src/main/java/com/gigker/server/domain/content/mapper/ContentApplyMapper.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentApplyService.java
  server/src/main/java/com/gigker/server/domain/review/service/ReviewService.java
  server/src/main/java/com/gigker/server/global/config/SecurityConfiguration.java
  server/src/test/java/com/gigker/server/domain/contentApply/ContentApplyServiceTest.java
Labels: feat, 🛠️ Backend

#87 [MEMBER] JWT Auth 통합 기능 구현
  server/appspec.yml
  server/build.gradle
  server/buildspec.yml
  server/scripts/initialize.sh
  server/scripts/server_clear.sh
  server/scripts/server_start.sh
  server/scripts/server_stop.sh
  server/src/main/java/com/gigker/server/domain/member/controller/MemberController.java
  server/src/main/java/com/gigker/server/domain/member/dto/MemberResponseDto.java
  server/src/main/java/com/gigker/server/domain/member/entity/Member.java
  server/src/main/java/com/gigker/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/gigker/server/domain/member/service/MemberService.java
  server/src/main/java/com/gigker/server/global/config/RedisConfig.java
  server/src/main/java/com/gigker/server/global/config/S3Config.java
  server/src/main/java/com/gigker/server/global/config/SecurityConfiguration.java
  server/src/main/java/com/gigker/server/global/exception/ExceptionCode.java
  server/src/main/java/com/gigker/server/global/security/controller/AuthController.java
  server/src/main/java/com/gigker/server/global/security/dto/LoginDto.java
  server/src/main/java/com/gigker/server/global/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/gigker/server/global/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/gigker/server/global/security/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/gigker/server/global/security/jwt/JwtTokenizer.java
  server/src/main/java/com/gigker/server/global/security/mapper/LoginMapper.java
  server/src/main/java/com/gigker/server/global/security/service/AuthService.java
  server/src/main/java/com/gigker/server/global/security/service/MemberDetailsService.java
Labels: feat, 🛠️ Backend

#92 로그인 & 로그아웃 기능 구현
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Navigation.tsx
  client/src/components/login/LogInForm.tsx
  client/src/components/signup/SignUpForm.tsx
  client/src/index.tsx
  client/src/util/cookie/index.ts
  client/src/util/logInApi.ts
Labels: feat, ✨ Frontend

#95 [MEMBER] 프론트에서 Refresh Header가 보이지않는 이슈 해결
  server/src/main/java/com/gigker/server/domain/member/mapper/ProfileMapper.java
  server/src/main/java/com/gigker/server/global/config/SecurityConfiguration.java
  server/src/main/resources/application.yml
  server/src/test/java/com/gigker/server/domain/stub/ContentStubData.java
Labels: 🛠️ Backend

#97 Be/feat/location
  server/src/main/java/com/gigker/server/domain/content/controller/ContentController.java
  server/src/main/java/com/gigker/server/domain/content/mapper/ContentMapper.java
  server/src/main/java/com/gigker/server/domain/content/repository/ContentRepository.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentService.java
Labels: 🛠️ Backend

#105 마이페이지 구현
  client/src/App.tsx
  client/src/components/Navigation.tsx
  client/src/components/login/LogInForm.tsx
  client/src/components/mypage/EditForm.tsx
  client/src/components/mypage/MyPageDetail.tsx
  client/src/pages/MyPage.tsx
  client/src/util/logInApi.ts
  client/src/util/redux/LogIn.ts
Labels: feat, ✨ Frontend

#113 feat/ 스케줄페이지 목업 구현 & 라우팅
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Navigation.tsx
  client/src/components/schedule/Calendar.tsx
  client/src/components/schedule/CalendarSide.tsx
  client/src/components/schedule/event-utils.tsx
  client/src/pages/Schedule.tsx
  client/src/util/redux/CalendarEvents.ts
  client/src/util/redux/index.ts
Labels: feat, ✨ Frontend

#103 [Schedule] 스케쥴 기능 구현
  server/src/main/java/com/gigker/server/domain/content/entity/Content.java
  server/src/main/java/com/gigker/server/domain/content/repository/ContentApplyRepository.java
  server/src/main/java/com/gigker/server/domain/schedule/controller/ScheduleController.java
  server/src/main/java/com/gigker/server/domain/schedule/dto/ScheduleResponseDto.java
  server/src/main/java/com/gigker/server/domain/schedule/mapper/ScheduleMapper.java
  server/src/main/java/com/gigker/server/domain/schedule/service/ScheduleService.java
  server/src/test/java/com/gigker/server/domain/contentApply/SchedulerTest.java
  server/src/test/java/com/gigker/server/domain/stub/ContentApplyStubData.java
  server/src/test/java/com/gigker/server/domain/stub/ContentStubData.java
Labels: feat, 🛠️ Backend

#115 Content patch fix
  server/src/main/java/com/gigker/server/domain/content/controller/ContentController.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentService.java
Labels: 🛠️ Backend

#122 로그인 시 두번 깜박이는 문제 수정
  client/src/assets/styles/global-styles.tsx
  client/src/components/Navigation.tsx
  client/src/components/hire/HireDropDown.tsx
  client/src/components/login/LogInForm.tsx
  client/src/components/mypage/EditForm.tsx
  client/src/components/mypage/MyPageDetail.tsx
  client/src/util/logInApi.ts
Labels: fix, design, ✨ Frontend

#127 [Style] CSS 수정
  client/src/assets/styles/global-styles.tsx
  client/src/components/Buttons.tsx
  client/src/components/Navigation.tsx
  client/src/components/hire/HireDropDown.tsx
  client/src/components/hunting/HuntingDropDown.tsx
  client/src/components/login/LogInForm.tsx
  client/src/components/signup/SignUpForm.tsx
  client/src/pages/LogInPage.tsx
  client/src/pages/SignUpPage.tsx
Labels: fix, design, ✨ Frontend

#123 [Member/ContentApply/Review] 회원의 평판 정보를 조회하는 로직 리팩터링 + @
  server/src/main/java/com/gigker/server/domain/content/controller/ContentApplyController.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentApplyResponseDto.java
  server/src/main/java/com/gigker/server/domain/content/entity/Content.java
  server/src/main/java/com/gigker/server/domain/content/entity/ContentApply.java
  server/src/main/java/com/gigker/server/domain/content/mapper/ContentApplyMapper.java
  server/src/main/java/com/gigker/server/domain/content/mapper/ContentMapper.java
  server/src/main/java/com/gigker/server/domain/content/repository/ContentApplyRepository.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentApplyService.java
  server/src/main/java/com/gigker/server/domain/member/controller/MemberController.java
  server/src/main/java/com/gigker/server/domain/member/dto/MemberResponseDto.java
  server/src/main/java/com/gigker/server/domain/member/entity/Member.java
  server/src/main/java/com/gigker/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/gigker/server/domain/review/controller/ReviewController.java
  server/src/main/java/com/gigker/server/domain/review/dto/ReviewDto.java
  server/src/main/java/com/gigker/server/domain/review/entity/Review.java
  server/src/main/java/com/gigker/server/domain/review/mapper/ReviewMapper.java
  server/src/main/java/com/gigker/server/domain/review/repository/ReviewRepository.java
  server/src/main/java/com/gigker/server/domain/review/service/ReviewService.java
  server/src/main/java/com/gigker/server/global/exception/ExceptionCode.java
Labels: fix, refactor, feat, 🛠️ Backend

#130 [Review] Response 누락된 부분 추가 및 수정
  server/src/main/java/com/gigker/server/domain/review/controller/ReviewController.java
  server/src/main/java/com/gigker/server/domain/review/dto/ReviewDto.java
  server/src/main/java/com/gigker/server/domain/review/entity/Review.java
  server/src/main/java/com/gigker/server/domain/review/mapper/ReviewMapper.java
  server/src/main/java/com/gigker/server/domain/review/service/ReviewService.java
Labels: feat, 🛠️ Backend

#133 [ContentApplyTest] 테스트 코드 리팩터링
  server/src/main/java/com/gigker/server/domain/content/controller/ContentApplyController.java
  server/src/main/java/com/gigker/server/domain/content/service/ContentApplyService.java
  server/src/main/java/com/gigker/server/domain/review/controller/ReviewController.java
  server/src/main/java/com/gigker/server/domain/review/service/ReviewService.java
  server/src/main/java/com/gigker/server/domain/schedule/controller/ScheduleController.java
  server/src/main/java/com/gigker/server/domain/schedule/service/ScheduleService.java
  server/src/main/java/com/gigker/server/global/exception/ExceptionCode.java
  server/src/test/java/com/gigker/server/domain/contentApply/ContentApplyServiceTest.java
  server/src/test/java/com/gigker/server/domain/contentApply/ContentApplyValidationUnitTest.java
  server/src/test/java/com/gigker/server/domain/stub/ContentApplyStubData.java
  server/src/test/java/com/gigker/server/domain/stub/ContentStubData.java
Labels: refactor, 🛠️ Backend

#142 [Content] 전체 게시글 조회 시 정보 누락된 부분 수정
  server/src/main/java/com/gigker/server/domain/content/controller/ContentController.java
  server/src/main/java/com/gigker/server/domain/content/dto/ContentResponseDto.java
  server/src/main/java/com/gigker/server/domain/content/mapper/ContentMapper.java
Labels: fix, 🛠️ Backend
